# Generated by Django 4.1.7 on 2023-04-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('category', models.CharField(max_length=200, verbose_name='Category')),
                ('client', models.CharField(max_length=200, verbose_name='Client')),
                ('date', models.DateField(verbose_name='Date')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio-images', verbose_name='Image')),
            ],
        ),
    ]
